name: Sync inventory data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * 1'

concurrency:
  group: stations-db
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mysql-to-sqlite3
      - name: Remove stale inventory data
        run: python -c "import sqlite3; c = sqlite3.connect('stations.db'); c.execute('DROP TABLE IF EXISTS inventory'); c.commit()"
      - name: Get inventory data
        run: mysql2sqlite -f stations.db -t inventory -d ${{ secrets.INVENTORY_DB }} -u ${{ secrets.INVENTORY_USER }} --mysql-password ${{ secrets.INVENTORY_PASSWORD }} -h ${{ secrets.INVENTORY_HOST }}
      - name: Upload stations database file via FTP
        run: |
          curl -T ./stations.db \
            --user "${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}" \
            -Q "-RNFR stations.db.tmp" -Q "-RNTO stations.db" \
            "ftp://${{ secrets.FTP_HOST }}/stations.db.tmp"
      - name: Commit Files
        run: |
          git config --local user.email "${{ vars.GIT_EMAIL }}"
          git config --local user.name "${{ vars.GIT_USER }}"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Sync inventory" --allow-empty)
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
